blank_issues_enabled: false
contact_links:
  - name: Twitter
    url: https://twitter.com/8004_scan
    about: Follow us for updates and announcements
  - name: Security Vulnerabilities
    url: https://github.com/alt-research/8004scan-issue-tracker/security/policy
    about: Please report security vulnerabilities through our security policy
